version: '3.8'

services:
  app:
    build: .  # Uses the Dockerfile to build the container
    container_name: express-ts-clock
    ports:
      - "3001:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "start"]  # Runs the app in development mode
  mysql_service:
    image: mysql:8
    container_name: express-ts-lock-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_clock
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - express_clock_mysql_data:/var/lib/mysql
volumes:
  express_clock_mysql_data: